<a href="https://colab.research.google.com/github/Eli0103/TalentoTech/blob/main/Taller_SQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#import library
import pandas as pd
import sqlite3

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
# Los datos de entrada están disponible están disponibles "drive".
path = "/content/drive/MyDrive/Colab Notebooks/Data/"

database = path + 'database.sqlite'

# creamos la conexión con BD y listaremos las tablas con las que contamos
conn = sqlite3.connect(database)
print ("conexión exitosa")

print(database)

conexión exitosa
/content/drive/MyDrive/Colab Notebooks/Data/database.sqlite

In [4]:
tables = pd.read_sql("""SELECT *
                        FROM sqlite_master
                        WHERE type='table';""", conn)
tables

,type,name,tbl_name,rootpage,sql
0,table,sqlite_sequence,sqlite_sequence,4,"CREATE TABLE sqlite_sequence(name,seq)"
1,table,Player_Attributes,Player_Attributes,11,"CREATE TABLE ""Player_Attributes"" (\n\t`id`\tIN..."
2,table,Player,Player,14,CREATE TABLE `Player` (\n\t`id`\tINTEGER PRIMA...
3,table,Match,Match,18,CREATE TABLE `Match` (\n\t`id`\tINTEGER PRIMAR...
4,table,League,League,24,CREATE TABLE `League` (\n\t`id`\tINTEGER PRIMA...
5,table,Country,Country,26,CREATE TABLE `Country` (\n\t`id`\tINTEGER PRIM...
6,table,Team,Team,29,"CREATE TABLE ""Team"" (\n\t`id`\tINTEGER PRIMARY..."
7,table,Team_Attributes,Team_Attributes,2,CREATE TABLE `Team_Attributes` (\n\t`id`\tINTE...

In [5]:
query = """SELECT *
            FROM Country; """
countries = pd.read_sql(query, conn)
countries

       id         name
0       1      Belgium
1    1729      England
2    4769       France
3    7809      Germany
4   10257        Italy
5   13274  Netherlands
6   15722       Poland
7   17642     Portugal
8   19694     Scotland
9   21518        Spain
10  24558  Switzerland

In [6]:
#consultar todas las ligas de futbol europeo
query = """SELECT *
            FROM league; """

#No modificar lo siguiente
league = pd.read_sql(query, conn)
league

       id  country_id                      name
0       1           1    Belgium Jupiler League
1    1729        1729    England Premier League
2    4769        4769            France Ligue 1
3    7809        7809     Germany 1. Bundesliga
4   10257       10257             Italy Serie A
5   13274       13274    Netherlands Eredivisie
6   15722       15722        Poland Ekstraklasa
7   17642       17642  Portugal Liga ZON Sagres
8   19694       19694   Scotland Premier League
9   21518       21518           Spain LIGA BBVA
10  24558       24558  Switzerland Super League

In [8]:
#consultar todas los jugadores de futbol europeo
query = """SELECT *
            FROM Player; """

players = pd.read_sql(query, conn)
players

DatabaseError: Execution failed on sql 'SELECT *
            FROM Player; ': database disk image is malformed

In [9]:
query = """SELECT *DISTINCT player_name FROM Player; """

pleyers_distinct = pd.read_sql(query, conn)
pleyers_distinct

DatabaseError: Execution failed on sql 'SELECT *DISTINCT player_name FROM Player; ': near "DISTINCT": syntax error