<a href="https://colab.research.google.com/github/Eli0103/TalentoTech/blob/main/Taller_SQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##TALLER SQL

##INTRODUCCIÓN

Usaré esta notebook para proporcionar una introducción a SQL, lenguaje imprescindible para todo analista de datos.

Los sistemas gestores de bases de datos interpretan consultas escritas en lenguaje SQL, y así es como interactuamos y obtenemos datos de las bases de datos y aplicaciones.

SQL significa Structured Query Language (Lenguaje de consulta estructurado)
SQL permite acceder y manipular bases de datos
SQL es una herramienta simple para el análisis avanzado de datos
SQL no se usa sólo para manipular datos, sino también para administrar la misma base de datos, crear y modificar el diseño de objetos de la base de datos, como tablas. El elemento de SQL que se usa para crear y modificar objetos de base de datos se denomina lenguaje de definición de datos (DDL). Este curso no trata DDL.

En esta notebook veremos cómo trabajar/manipular tablas. Aprenderemos a usar SQL para interactuar con una base de datos de fútbol europeo y generar información interesante con sus datos.

La base de datos utilizada, pueder ser encontrada aquí

1.1 Definiciones importantes
Aunque SQL es un estándar ANSI/ISO, existen diferentes versiones del lenguaje SQL. Sin embargo, para cumplir con el estándar del American National Standards Institute (ANSI), todas las versiones deben soportar al menos los comandos principales (como SELECT, UPDATE, DELETE, INSERT, WHERE) de forma similar.

En este caso, vamos a trabajar con SQLite que es una implementación específica. La mayoría de los lenguajes SQL comparten todas las capacidades de este notebook. Las diferencias suelen estar en el rendimiento y en las funcionalidades analíticas avanzadas (y a veces en los errores, por supuesto).

1.2 ¿Qué es SQLite?
SQLite es una biblioteca de software que proporciona un sistema de gestión de bases de datos relacionales que se puede utilizar en casi todos los lenguajes de programación, incluido Python.

El lite en SQLite significa facilidad en términos de configuración, administración de la base de datos y recursos necesarios. Las siguientes son sus características más importantes: es autónomo, sin servidor y transaccional.

Más información acerca de SQLite: https://www.sqlitetutorial.net/

1.2.1 Configuraciones previas
SQLite se puede utilizar en casi todos los lenguajes de programación, incluido Python. Esta notebook corre en Python, por lo que vamos a importar la librería de SQLite y otras que nos pueden ser de utilidad más adelante.

Asimismo, crearemos la conexión con la BD y listaremos las tablas con las que contamos.

Ejecuta (haciendo clic en ejecutar o Shift+Enter) el códido de abajo

In [1]:
#import library
import pandas as pd
import sqlite3

In [26]:
#Lectura del Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [27]:
# Los datos de entrada están disponible están disponibles "drive".
# Se sugier establecer la conexión con su drive personal
path = "/content/drive/MyDrive/Colab Notebooks/Data/"

database = path + 'database.sqlite'

# creamos la conexión con BD y listaremos las tablas con las que contamos
conn = sqlite3.connect(database)
print ("conexión exitosa")

print(database)

conexión exitosa
/content/drive/MyDrive/Colab Notebooks/Data/database.sqlite

2. Sentencia SELECT

Esta es la consulta más básica y su estructura es muy simple:

Se define lo que se quiere ver después del SELECT
Se eligen las tablas a consultar después del FROM
Las únicas partes imprescindibles de una consulta son el SELECT y el FROM.

La sintaxis de esta consulta es así:

SELECT column1, column2, ...

FROM table_name;

Para consultar por todos los campos en una tabla sin tener que escribir uno por uno el nombre de cada campo, se utiliza SELECT *

SELECT * significa que quieres obtener todas las columnas posibles de la tabla consultada. Los datos devueltos se almacenan en una tabla de resultados, denominada conjunto de resultados.

La sintaxis de esta consulta es así:

SELECT *

FROM table_name;

Es una buena práctica terminar la consulta con un punto y coma para indicar que la consulta está completa. Las palabras clave se escriben en mayúsculas y los nombres de tablas y campos se escriben en minúsculas.

2. Sentencia SELECT
Esta es la consulta más básica y su estructura es muy simple:

Se define lo que se quiere ver después del SELECT
Se eligen las tablas a consultar después del FROM
Las únicas partes imprescindibles de una consulta son el SELECT y el FROM.

La sintaxis de esta consulta es así:

SELECT column1, column2, ...

FROM table_name;

Para consultar por todos los campos en una tabla sin tener que escribir uno por uno el nombre de cada campo, se utiliza SELECT *

SELECT * significa que quieres obtener todas las columnas posibles de la tabla consultada. Los datos devueltos se almacenan en una tabla de resultados, denominada conjunto de resultados.

La sintaxis de esta consulta es así:

SELECT *

FROM table_name;

Es una buena práctica terminar la consulta con un punto y coma para indicar que la consulta está completa. Las palabras clave se escriben en mayúsculas y los nombres de tablas y campos se escriben en minúsculas.

In [4]:
#Listaremos las tablas con las que contamos
tables = pd.read_sql("""SELECT *
                        FROM sqlite_master
                        WHERE type='table';""", conn)
tables

,type,name,tbl_name,rootpage,sql
0,table,sqlite_sequence,sqlite_sequence,4,"CREATE TABLE sqlite_sequence(name,seq)"
1,table,Player_Attributes,Player_Attributes,11,"CREATE TABLE ""Player_Attributes"" (\n\t`id`\tIN..."
2,table,Player,Player,14,CREATE TABLE `Player` (\n\t`id`\tINTEGER PRIMA...
3,table,Match,Match,18,CREATE TABLE `Match` (\n\t`id`\tINTEGER PRIMAR...
4,table,League,League,24,CREATE TABLE `League` (\n\t`id`\tINTEGER PRIMA...
5,table,Country,Country,26,CREATE TABLE `Country` (\n\t`id`\tINTEGER PRIM...
6,table,Team,Team,29,"CREATE TABLE ""Team"" (\n\t`id`\tINTEGER PRIMARY..."
7,table,Team_Attributes,Team_Attributes,2,CREATE TABLE `Team_Attributes` (\n\t`id`\tINTE...

2.1.1 Ejemplo: Listar los países Queremos consultar qué países se encuentran en la tabla Country de la base de datos del fútbol europeo.

Importante: La estructura y el orden de las secciones son importantes, mientras que los espacios, las nuevas líneas, las mayúsculas y las sangrías están ahí para facilitar la lectura del código.

Ejecuta (haciendo clic en ejecutar o Shift+Enter) el códido de abajo

In [5]:
query = """SELECT *
            FROM Country; """
countries = pd.read_sql(query, conn)
countries

       id         name
0       1      Belgium
1    1729      England
2    4769       France
3    7809      Germany
4   10257        Italy
5   13274  Netherlands
6   15722       Poland
7   17642     Portugal
8   19694     Scotland
9   21518        Spain
10  24558  Switzerland

2.1.2 Práctica: Listar las ligas del fútbol europeo
Deben listar todas las ligas que estén en la tabla League de la base de datos de fútbol europeo.

Para ello deberán escribir la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" justo después de la palabra query =

Una vez que estén lo tengan listo, ejecuten haciendo clic en ejecutar (o Shift+Enter) el códido de abajo

In [6]:
#consultar todas las ligas de futbol europeo
query = """SELECT *
            FROM league; """

#No modificar lo siguiente
league = pd.read_sql(query, conn)
league

       id  country_id                      name
0       1           1    Belgium Jupiler League
1    1729        1729    England Premier League
2    4769        4769            France Ligue 1
3    7809        7809     Germany 1. Bundesliga
4   10257       10257             Italy Serie A
5   13274       13274    Netherlands Eredivisie
6   15722       15722        Poland Ekstraklasa
7   17642       17642  Portugal Liga ZON Sagres
8   19694       19694   Scotland Premier League
9   21518       21518           Spain LIGA BBVA
10  24558       24558  Switzerland Super League

2.1.3 Práctica: Listar los jugadores del fútbol europeo
Deben listar los campos id,player_name, birthday, height y weight que estan en la tabla Player de la base de datos de Fútbol Europeo.

Para ello deberán escribir la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

Una vez que estén lo tengan listo, ejecuten (haciendo clic en ejecutar o Shift+Enter) el códido de abajo

In [7]:
#consultar o listar todos los jugadores de futbol europeo
query = """SELECT *
            FROM Player; """

players = pd.read_sql(query, conn)
players

,id,player_api_id,player_name,player_fifa_api_id,birthday,height,weight
0,1,505942,Aaron Appindangoye,218353,1992-02-29 00:00:00,182.88,187
1,2,155782,Aaron Cresswell,189615,1989-12-15 00:00:00,170.18,146
2,3,162549,Aaron Doran,186170,1991-05-13 00:00:00,170.18,163
3,4,30572,Aaron Galindo,140161,1982-05-08 00:00:00,182.88,198
4,5,23780,Aaron Hughes,17725,1979-11-08 00:00:00,182.88,154
...,...,...,...,...,...,...,...
11055,11071,26357,Zoumana Camara,2488,1979-04-03 00:00:00,182.88,168
11056,11072,111182,Zsolt Laczko,164680,1986-12-18 00:00:00,182.88,176
11057,11073,36491,Zsolt Low,111191,1979-04-29 00:00:00,180.34,154
11058,11074,35506,Zurab Khizanishvili,47058,1981-10-06 00:00:00,185.42,172
11059,11075,39902,Zvjezdan Misimovic,102359,1982-06-05 00:00:00,180.34,176

In [8]:
#Listar los juegos de los equipos de futbol europeo,
query = """SELECT DISTINCT player_name FROM Player; """

players_distinct = pd.read_sql(query, conn)
players_distinct

               player_name
0       Aaron Appindangoye
1          Aaron Cresswell
2              Aaron Doran
3            Aaron Galindo
4             Aaron Hughes
...                    ...
10843       Zoumana Camara
10844         Zsolt Laczko
10845            Zsolt Low
10846  Zurab Khizanishvili
10847   Zvjezdan Misimovic

[10848 rows x 1 columns]

In [9]:
query = """SELECT * FROM Match; """
Matches = pd.read_sql(query, conn)
Matches

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,...,SJA,VCH,VCD,VCA,GBH,GBD,GBA,BSH,BSD,BSA
0,1,1,1,2008/2009,1,2008-08-17 00:00:00,492473,9987,9993,1,...,4.00,1.65,3.40,4.50,1.78,3.25,4.00,1.73,3.40,4.20
1,2,1,1,2008/2009,1,2008-08-16 00:00:00,492474,10000,9994,0,...,3.80,2.00,3.25,3.25,1.85,3.25,3.75,1.91,3.25,3.60
2,3,1,1,2008/2009,1,2008-08-16 00:00:00,492475,9984,8635,0,...,2.50,2.35,3.25,2.65,2.50,3.20,2.50,2.30,3.20,2.75
3,4,1,1,2008/2009,1,2008-08-17 00:00:00,492476,9991,9998,5,...,7.50,1.45,3.75,6.50,1.50,3.75,5.50,1.44,3.75,6.50
4,5,1,1,2008/2009,1,2008-08-16 00:00:00,492477,7947,9985,1,...,1.73,4.50,3.40,1.65,4.50,3.50,1.65,4.75,3.30,1.67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25974,25975,24558,24558,2015/2016,9,2015-09-22 00:00:00,1992091,10190,10191,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25975,25976,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992092,9824,10199,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25976,25977,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992093,9956,10179,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25977,25978,24558,24558,2015/2016,9,2015-09-22 00:00:00,1992094,7896,10243,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25978,25979,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992095,10192,9931,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

2.2 Sentencia SELECT DISTINCT
La sentencia SELECT DISTINCT se utiliza para devolver sólo valores distintos (diferentes).

Dentro de una tabla, una columna a menudo contiene muchos valores duplicados y a veces sólo se desea listar los diferentes valores (distintos).

La sintaxis de SELECT DISTINCT es así:

SELECT DISTINCT column1

FROM table_name;

2.2.1 Listar las temporadas jugadas de esta Base de Datos
Si consultamos por todas las temporadas que se almacenaron en la tabla Matchde la base de datos de Fútbol Europeo, vamos a tener el siguiente resultado.

Ejecuta (haciendo clic en ejecutar o Shift+Enter) el códido de abajo

In [10]:
query = """
SELECT season
FROM Match;
"""
seasons = pd.read_sql(query, conn)
seasons

          season
0      2008/2009
1      2008/2009
2      2008/2009
3      2008/2009
4      2008/2009
...          ...
25974  2015/2016
25975  2015/2016
25976  2015/2016
25977  2015/2016
25978  2015/2016

[25979 rows x 1 columns]

In [11]:
query = """SELECT*
            FROM Player_Attributes;"""

atributos = pd.read_sql(query, conn)
atributos

,id,player_fifa_api_id,player_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
0,1,218353,505942,2016-02-18 00:00:00,67.0,71.0,right,medium,medium,49.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
1,2,218353,505942,2015-11-19 00:00:00,67.0,71.0,right,medium,medium,49.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
2,3,218353,505942,2015-09-21 00:00:00,62.0,66.0,right,medium,medium,49.0,...,54.0,48.0,65.0,66.0,69.0,6.0,11.0,10.0,8.0,8.0
3,4,218353,505942,2015-03-20 00:00:00,61.0,65.0,right,medium,medium,48.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
4,5,218353,505942,2007-02-22 00:00:00,61.0,65.0,right,medium,medium,48.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183973,183974,102359,39902,2009-08-30 00:00:00,83.0,85.0,right,medium,low,84.0,...,88.0,83.0,22.0,31.0,30.0,9.0,20.0,84.0,20.0,20.0
183974,183975,102359,39902,2009-02-22 00:00:00,78.0,80.0,right,medium,low,74.0,...,88.0,70.0,32.0,31.0,30.0,9.0,20.0,73.0,20.0,20.0
183975,183976,102359,39902,2008-08-30 00:00:00,77.0,80.0,right,medium,low,74.0,...,88.0,70.0,32.0,31.0,30.0,9.0,20.0,73.0,20.0,20.0
183976,183977,102359,39902,2007-08-30 00:00:00,78.0,81.0,right,medium,low,74.0,...,88.0,53.0,28.0,32.0,30.0,9.0,20.0,73.0,20.0,20.0
183977,183978,102359,39902,2007-02-22 00:00:00,80.0,81.0,right,medium,low,74.0,...,88.0,53.0,38.0,32.0,30.0,9.0,9.0,78.0,7.0,15.0

2.2 Sentencia SELECT DISTINCT
La sentencia SELECT DISTINCT se utiliza para devolver sólo valores distintos (diferentes).

Dentro de una tabla, una columna a menudo contiene muchos valores duplicados y a veces sólo se desea listar los diferentes valores (distintos).

La sintaxis de SELECT DISTINCT es así:

SELECT DISTINCT column1

FROM table_name;

In [12]:
query = """SELECT DISTINCT season FROM Match;"""
seasons = pd.read_sql(query, conn)
seasons

      season
0  2008/2009
1  2009/2010
2  2010/2011
3  2011/2012
4  2012/2013
5  2013/2014
6  2014/2015
7  2015/2016

2.2.2 Práctica: Listar sólo tasas diferentes de valoración general de los jugadores.
En la tabla Player_Attributes de la base de datos de Fútbol Europeo hay el campo overall_rating que parece contener la valoración de los jugadores. El objetivo es ver sólo tasas diferentes de valoración general de los jugadores.

Para ello deberán escribir la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

Una vez que estén lo tengan listo, ejecuten (haciendo clic en ejecutar o Shift+Enter) el códido de abajo

In [13]:
query = """SELECT DISTINCT overall_rating FROM Player_Attributes;"""

valoracion = pd.read_sql(query, conn)
valoracion

    overall_rating
0             67.0
1             62.0
2             61.0
3             74.0
4             73.0
..             ...
57            33.0
58            36.0
59            37.0
60            35.0
61            94.0

[62 rows x 1 columns]

3. Sentencia LIMIT
Cuando deseamos poner un límite al resultado o no nos interesa conocer la totalidad de los resultados, podemos limitar la cantidad de registros resultantes mediante la sentencia LIMIT

La sintaxis de LIMIT es así:

SELECT column1, column2...

FROM table_name

LIMIT number;

3.1.1 Ejemplo: Listar 15 jugadores de la base de datos del fútbol europeo¶
Queremos listar 15 jugadores de la tabla Player de la base de datos de Fútbol Europeo. En la tabla de resultados quiero ver los campos ìd,player_name, birthday, height y weight. Todos se encuentran en la tabla Player

Ejecuta (haciendo clic en ejecutar o Shift+Enter) el códido de abajo

3. Sentencia LIMIT
Cuando deseamos poner un límite al resultado o no nos interesa conocer la totalidad de los resultados, podemos limitar la cantidad de registros resultantes mediante la sentencia LIMIT

La sintaxis de LIMIT es así:

SELECT column1, column2...

FROM table_name

LIMIT number;

In [14]:
query = """SELECT id, player_name, birthday, height, weight
FROM Player
LIMIT 15; """

juagadores = pd.read_sql(query, conn)
juagadores

    id         player_name             birthday  height  weight
0    1  Aaron Appindangoye  1992-02-29 00:00:00  182.88     187
1    2     Aaron Cresswell  1989-12-15 00:00:00  170.18     146
2    3         Aaron Doran  1991-05-13 00:00:00  170.18     163
3    4       Aaron Galindo  1982-05-08 00:00:00  182.88     198
4    5        Aaron Hughes  1979-11-08 00:00:00  182.88     154
5    6          Aaron Hunt  1986-09-04 00:00:00  182.88     161
6    7          Aaron Kuhl  1996-01-30 00:00:00  172.72     146
7    8        Aaron Lennon  1987-04-16 00:00:00  165.10     139
8    9        Aaron Lennox  1993-02-19 00:00:00  190.50     181
9   10       Aaron Meijers  1987-10-28 00:00:00  175.26     170
10  11       Aaron Mokoena  1980-11-25 00:00:00  182.88     181
11  12          Aaron Mooy  1990-09-15 00:00:00  175.26     150
12  13      Aaron Muirhead  1990-08-30 00:00:00  187.96     168
13  14        Aaron Niguez  1989-04-26 00:00:00  170.18     143
14  15        Aaron Ramsey  1990-12-26 00:00:00  177.80     154

3.1.2 Práctica: Listar 25 equipos del fútbol europeo
Deben listar 25 equipos del fútbol europeo. La tabla de resultados deberá contener los campos id y team_long_name de la tabla Team de la base de datos de Fútbol Europeo.

Para ello deberán escribir la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

Una vez que estén lo tengan listo, ejecuten (haciendo clic en ejecutar o Shift+Enter) el códido de abajo

In [15]:
query = """SELECT id, team_long_name
FROM Team LIMIT 25;"""

Teams = pd.read_sql(query, conn)
Teams

      id        team_long_name
0      1              KRC Genk
1      2          Beerschot AC
2      3      SV Zulte-Waregem
3      4      Sporting Lokeren
4      5     KSV Cercle Brugge
5      6        RSC Anderlecht
6      7              KAA Gent
7      8             RAEC Mons
8      9         FCV Dender EH
9     10     Standard de Liège
10    11           KV Mechelen
11    12        Club Brugge KV
12    13         KSV Roeselare
13    14           KV Kortrijk
14    15                Tubize
15    16  Royal Excel Mouscron
16    17          KVC Westerlo
17    18    Sporting Charleroi
18   614     Sint-Truidense VV
19  1034             Lierse SK
20  1042             KAS Eupen
21  1513   Oud-Heverlee Leuven
22  2004      Waasland-Beveren
23  2476           KV Oostende
24  2510  Royal Excel Mouscron

##4. Funciones agregativas/ Métricas
Todas las métricas tienen que ser agregadas usando funciones. Las funciones agregativas más comunes son:

SUM() | Sumatoria total de una columna tipo numérica.
COUNT() | Devuelve la cantidad de filas.
COUNT(DISTINCT) | Devuelve la cantidad de filas distintas o diferentes.
AVG() | Promedia los valores de una columna tipo numérica.
MIN() | Menor valor dentro de la columna especificada.
MAX() | Mayor valor dentro de la columna especificada.

##La sintaxis de las métricas en la sentencia SELECT es así:

SUM() SELECT SUM(column1), column2...

FROM table_name

COUNT() SELECT COUNT(column1), column2...

FROM table_name

COUNT(DISTINCT) SELECT COUNT(DISTINCT column1), column2...

FROM table_name

AVG() SELECT AVG(column1), column2...

FROM table_name

MIN() SELECT MIN(column1), column2...

FROM table_name

MAX() SELECT MAX(column1), column2...

FROM table_name

4.1.1 Ejemplo: ¿Cuántos países diferentes están almacenados en la tabla Country?
Para consultar por el número de países diferentes almacenados en la tabla Country y que la tabla de resultados nos muestre únicamente el número con la cantidad de países, necesitamos usar una función agregativa que cuente el número de registros pero además, que cuente sólo los registros distintos. Esa función es COUNT(DISTINCT )

Ejecuten (haciendo clic en ejecutar o Shift+Enter) el códido de abajo

In [29]:
#Ingrese la la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

query = """
SELECT COUNT(DISTINCT name) as Numero_Paises
FROM Country;
"""

#No modificar lo siguiente:
count_countries = pd.read_sql(query, conn)
count_countries

   Numero_Paises
0             11

4.1.2 Práctica: Traer el número de etapas jugadas de la tabla Match
Deben traer el número de etapas stage almacenados en la tabla Match de la base de datos de Fútbol Europeo. La tabla de resultados deberá mostrar únicamente el número con la cantidad de etapas diferentes.

Para ello deberán escribir la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

Una vez que estén lo tengan listo, ejecuten (haciendo clic en ejecutar o Shift+Enter) el códido de abajo

In [16]:
query = """SELECT * FROM  Match;"""
match_des= pd.read_sql(query, conn)
match_des

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,...,SJA,VCH,VCD,VCA,GBH,GBD,GBA,BSH,BSD,BSA
0,1,1,1,2008/2009,1,2008-08-17 00:00:00,492473,9987,9993,1,...,4.00,1.65,3.40,4.50,1.78,3.25,4.00,1.73,3.40,4.20
1,2,1,1,2008/2009,1,2008-08-16 00:00:00,492474,10000,9994,0,...,3.80,2.00,3.25,3.25,1.85,3.25,3.75,1.91,3.25,3.60
2,3,1,1,2008/2009,1,2008-08-16 00:00:00,492475,9984,8635,0,...,2.50,2.35,3.25,2.65,2.50,3.20,2.50,2.30,3.20,2.75
3,4,1,1,2008/2009,1,2008-08-17 00:00:00,492476,9991,9998,5,...,7.50,1.45,3.75,6.50,1.50,3.75,5.50,1.44,3.75,6.50
4,5,1,1,2008/2009,1,2008-08-16 00:00:00,492477,7947,9985,1,...,1.73,4.50,3.40,1.65,4.50,3.50,1.65,4.75,3.30,1.67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25974,25975,24558,24558,2015/2016,9,2015-09-22 00:00:00,1992091,10190,10191,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25975,25976,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992092,9824,10199,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25976,25977,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992093,9956,10179,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25977,25978,24558,24558,2015/2016,9,2015-09-22 00:00:00,1992094,7896,10243,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25978,25979,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992095,10192,9931,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
#Traer el número de etapas jugadas de la tabla
query = """SELECT COUNT(DISTINCT stage) AS conteo_Temporadas FROM Match; """

#No modificar lo siguiente:
countdis_stages = pd.read_sql(query, conn)
countdis_stages

#En todas las ligas Europeas en el periodo de tiempo de 2008 al 2016 se jugaron 38 etapas

   conteo_Temporadas
0                 38

In [18]:
query = """SELECT * FROM Match WHERE stage = 1 AND season ='2008/2009' """

#No modificar lo siguiente:
count_stage = pd.read_sql(query, conn)
count_stage

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,...,SJA,VCH,VCD,VCA,GBH,GBD,GBA,BSH,BSD,BSA
0,1,1,1,2008/2009,1,2008-08-17 00:00:00,492473,9987,9993,1,...,4.00,1.65,3.40,4.50,1.78,3.25,4.00,1.73,3.40,4.20
1,2,1,1,2008/2009,1,2008-08-16 00:00:00,492474,10000,9994,0,...,3.80,2.00,3.25,3.25,1.85,3.25,3.75,1.91,3.25,3.60
2,3,1,1,2008/2009,1,2008-08-16 00:00:00,492475,9984,8635,0,...,2.50,2.35,3.25,2.65,2.50,3.20,2.50,2.30,3.20,2.75
3,4,1,1,2008/2009,1,2008-08-17 00:00:00,492476,9991,9998,5,...,7.50,1.45,3.75,6.50,1.50,3.75,5.50,1.44,3.75,6.50
4,5,1,1,2008/2009,1,2008-08-16 00:00:00,492477,7947,9985,1,...,1.73,4.50,3.40,1.65,4.50,3.50,1.65,4.75,3.30,1.67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89,24558,24558,24558,2008/2009,1,2008-09-23 00:00:00,486262,9956,6493,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90,24559,24558,24558,2008/2009,1,2008-07-18 00:00:00,486263,10192,9931,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91,24560,24558,24558,2008/2009,1,2008-07-19 00:00:00,486264,9930,10179,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,24561,24558,24558,2008/2009,1,2008-07-20 00:00:00,486265,10199,9824,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93,24562,24558,24558,2008/2009,1,2008-07-20 00:00:00,486266,7955,10243,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

4.1.3 Práctica: Traer la suma de goles hechos por los equipos visitantes de la tabla Match¶
Deben traer la suma de goles hechos por los equipos visitantes away_team_goal almacenados en la tabla Match de la base de datos de Fútbol Europeo. La tabla de resultados deberá mostrar únicamente el número con la suma de goles.

Para ello deberán escribir la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

Una vez que estén lo tengan listo, ejecuten (haciendo clic en ejecutar o Shift+Enter) el códido de abajo

In [30]:
query = """SELECT sum(away_team_goal) AS Goles_Visit FROM Match"""

#No modificar lo siguiente:
sum_awayteam = pd.read_sql(query, conn)
sum_awayteam

   Goles_Visit
0        30160

4.1.4 Práctica: Traer el promedio de goles hechos por los equipos locales y el promedio de goles hechos por los visitantes de la tabla Match¶
Deben traer el promedio de goles hechos por los equipos locales home_team_goal y el promedio de goles hechos por los equipos visitantes away_team_goal almacenados en la tabla Match de la base de datos de Fútbol Europeo. La tabla de resultados deberá mostrar únicamente el número con el promedio de goles.

Para ello deberán escribir la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

Una vez que estén lo tengan listo, ejecuten (haciendo clic en ejecutar o Shift+Enter) el códido de abajo

In [39]:
#Ingrese la la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

query = """SELECT AVG(home_team_goal) AS avg_home_team_goal,   AVG(away_team_goal) AS avg_away_team_goal FROM Match; """

#No modificar lo siguiente:
avg_teamgoals = pd.read_sql(query, conn)
avg_teamgoals

   avg_home_team_goal  avg_away_team_goal
0            1.544594            1.160938

4.1.5 Práctica: Traer la máxima cantidad de goles que un equipo visitante anotó en los juegos de la tabla Match
Deben traer la máxima cantidad de goles un equipo visitante away_team_goal almacenados en la tabla Match de la base de datos de Fútbol Europeo. La tabla de resultados deberá mostrar únicamente el número con cantidad de goles.

Para ello deberán escribir la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

Una vez que estén lo tengan listo, ejecuten (haciendo clic en ejecutar o Shift+Enter) el códido de abajo

In [42]:
#Ingrese la la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

query = """ SELECT MAX(away_team_goal) FROM Match;"""

#No modificar lo siguiente:
max_teamgoals = pd.read_sql(query, conn)
max_teamgoals

   MAX(away_team_goal)
0                    9

5. Operaciones matemáticas¶
Se pueden realizar operaciones matemáticas como: +, -, *, /, etc. Asimismo, estás operaciones pueden ser usadas en conjunto con las funciones agregativas/ métricas.

La sintaxis en la sentencia SELECT es así:

+
SELECT column1+column2

FROM table_name

La sintaxis combinando con una métrica en la sentencia SELECT es así:

AVG(+)
SELECT AVG(column1+column2)

FROM table_name

5.1.1 Práctica: Traer el promedio de goles por partido de la tabla Match
Deben traer el promedio de la suma de goles hechos por los equipos locales home_team_goal y visitantes away_team_goal en todos los juegos almacenados en la tabla Match de la base de datos de Fútbol Europeo. La tabla de resultados deberá mostrar únicamente el número con el promedio de goles por partido.

Para ello deberán escribir la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

Una vez que estén lo tengan listo, ejecuten (haciendo clic en ejecutar o Shift+Enter) el códido de abajo

In [47]:
#Ingrese la la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

query = """SELECT AVG(home_team_goal + away_team_goal) AS avg_goals_por_partido
FROM Match;
"""

#No modificar lo siguiente:
avg_sum_goals = pd.read_sql(query, conn)
avg_sum_goals

   avg_goals_por_partido
0               2.705531

6. Sentencia WHERE
La sentencia WHERE se utiliza para filtrar registros. Mediante esta sentencia, se extraen sólo aquellos registros que cumplen una condición específica.

La sintaxis de WHERE es así:

SELECT column1, column2...

FROM table_name

WHERE condition;

6.1 Campos de texto (y fecha) vs campos numéricos¶
SQL requiere comillas simples alrededor de los valores del texto y fecha (la mayoría de los sistemas de bases de datos también permiten comillas dobles). Sin embargo, los campos numéricos no deben incluirse entre comillas.

Ejemplos de sintaxis con campo númerico:

SELECT *

FROM Customers

WHERE CustomerId = 1;

Ejemplos de sintaxis con campo de texto:

SELECT *

FROM Customers

WHERE Country = 'Mexico';

6.2.1 Ejemplo: Listar los jugadores que pesan 165 libras
Queremos listar a los jugadores que cumplan con la condición de pesar 165 libras. En la tabla de resultados quiero ver los campos id,player_name, birthday, height y weight de los que cumplen la condición. Todos se encuentran en la tabla Player

Ejecuta (haciendo clic en ejecutar o Shift+Enter) el códido de abajo

In [48]:
query = """SELECT id, player_name, birthday, height, weight
        FROM Player
        WHERE weight = 165
        LIMIT 15;"""

players_weight = pd.read_sql(query, conn)
players_weight

     id          player_name             birthday  height  weight
0    27   Abdelmalek Cherrad  1981-01-14 00:00:00  185.42     165
1    44   Abdoulaye Doucoure  1993-01-01 00:00:00  182.88     165
2    46      Abdoulaye Keita  1994-01-05 00:00:00  175.26     165
3    49  Abdoulwahid Sissoko  1990-03-20 00:00:00  182.88     165
4    58   Abdullah Al Hafith  1992-12-25 00:00:00  187.96     165
5    62           Abel Gomez  1982-02-20 00:00:00  182.88     165
6    67                 Abel  1978-12-22 00:00:00  177.80     165
7    69         Abiola Dauda  1988-02-03 00:00:00  180.34     165
8    78     Abraham Paz Cruz  1979-03-14 00:00:00  177.80     165
9    84          Aco Stojkov  1983-04-29 00:00:00  177.80     165
10  110            Adam King  1995-10-11 00:00:00  180.34     165
11  119       Adam Matuschyk  1989-02-14 00:00:00  180.34     165
12  132            Adam Vass  1988-09-09 00:00:00  180.34     165
13  157        Adnan Januzaj  1995-02-05 00:00:00  182.88     165
14  169   Adrian Klepczynski  1981-04-01 00:00:00  187.96     165

6.2.2 Práctica: Listar las temporadas en que un equipo visitante anotó 7 o más goles
Deben listar las temporadas en que algún equipo visitante haya anotado 7 o más goles. La tabla de resultados deberá contener los campos season, home_team_goal, away_team_goal de la tabla Match de la base de datos de Fútbol Europeo.

Para ello deberán escribir la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

Una vez que estén lo tengan listo, ejecuten (haciendo clic en ejecutar o Shift+Enter) el códido de abajo

In [56]:
#Ingrese la la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

query = """SELECT season, home_team_goal, away_team_goal FROM Match WHERE away_team_goal >= 7;"""

#No modificar lo siguiente:
away_team_goals = pd.read_sql(query, conn)
away_team_goals

       season  home_team_goal  away_team_goal
0   2012/2013               1               7
1   2014/2015               1               7
2   2014/2015               2               7
3   2015/2016               0               9
4   2010/2011               1               8
5   2013/2014               0               7
6   2010/2011               0               7
7   2013/2014               0               7
8   2010/2011               0               8
9   2011/2012               0               7
10  2014/2015               0               8
11  2014/2015               2               8
12  2015/2016               0               8
13  2008/2009               1               7
14  2009/2010               1               7
15  2015/2016               0               7

6.3 Operadores lógicos en WHERE
La sentencia WHERE puede combinarse con los operadores lógicos: AND, OR y NOT. Los operadores AND y OR se utilizan para filtrar registros basados en más de una condición.

El operador AND muestra un registro si todas las condiciones separadas por AND son VERDADERA(s).
El operador OR muestra un registro si alguna de las condiciones separadas por OR es VERDADERA(s).
El operador NOT muestra un registro si la(s) condición(es) NO es VERDADERA(s).
Sintaxis deAND:
SELECT column1, column2, ...

FROM table_name

WHERE condition1 AND condition2 AND condition3 ...;

Sintaxis de OR
SELECT column1, column2, ...

FROM table_name

WHERE condition1 OR condition2 ...;

Sintaxis de NOT
SELECT column1, column2, ...

FROM table_name

WHERE NOT condition;

6.3.1 Práctica: Traer el Id de los equipos que desarrollan un dribbling normal y su velocidad de juego es balanceada
Tomando la tabla Team_Attributes de la base de datos de Fútbol Europeo, deben obtener el id,buildUpPlayDribblingClass y buildUpPlaySpeedClass de los equipos que tengan los siguientes atributos:

buildUpPlayDribblingClass = 'Normal'
buildUpPlaySpeedClass = 'Balanced'
Para ello deberán escribir la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

Una vez que estén lo tengan listo, ejecuten (haciendo clic en ejecutar o Shift+Enter) el códido de abajo

In [60]:
#Ingrese la la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

query = """SELECT id, buildUpPlayDribblingClass, buildUpPlaySpeedClass
FROM Team_Attributes
WHERE buildUpPlayDribblingClass = 'Normal' AND buildUpPlaySpeedClass = 'Balanced';
"""

#No modificar lo siguiente:
team_att_and = pd.read_sql(query, conn)
team_att_and

       id buildUpPlayDribblingClass buildUpPlaySpeedClass
0       2                    Normal              Balanced
1       3                    Normal              Balanced
2       8                    Normal              Balanced
3       9                    Normal              Balanced
4      14                    Normal              Balanced
..    ...                       ...                   ...
382  1450                    Normal              Balanced
383  1451                    Normal              Balanced
384  1452                    Normal              Balanced
385  1457                    Normal              Balanced
386  1458                    Normal              Balanced

[387 rows x 3 columns]

6.4 Otros operadores que trabajan con la sentencia WHERE
Los siguientes operadores también pueden ser utilizados en la sentencia WHERE:

| = | Igual

| > | Mayor que

| < | Menor que

| >= | Mayor o igual que

| <= | Menor o igual que

| <> | No igual. Nota: En algunas versiones de SQL este operador puede ser escrito como !=

| BETWEEN | Entre cierto rango

| LIKE | Para consultar los datos basados en información parcial, se utiliza el operador LIKE en la sentencia WHERE. Busca un patrón. El patrón va antes, después o entre un par de % (wildcard). Ejemplo: LIKE 's%' busca cualquier texto que comience con 's'. LIKE '%er' busca cualquier texto que termine con 'er'. Y LIKE '%per%' busca cualquier texto que contenga 'per'.

| IN | Para especificar varios valores posibles para una columna o subquery. Ejemplo de sintaxis cuando se especifica varios valores:

SELECT column1
FROM Table_name
WHERE column1 IN (value1, value2);.

Ejemplo se sintaxis cuando se usa IN en una subquery:

SELECT TrackId, Name, AlbumId
FROM Tracks
WHERE AlbumId IN
    (SELECT AlbumId
    FROM Albums
    WHERE ArtistId = 12);.

6.4.1 Práctica: Traer la tabla de países únicamente con Italia
Deben filtrar la tabla de países y traer únicamente a Italy. La tabla de resultados deberá contener los campos id y name de la tabla Country de la base de datos de Fútbol Europeo.

Para ello deberán escribir la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

Una vez que estén lo tengan listo, ejecuten (haciendo clic en ejecutar o Shift+Enter) el códido de abajo

In [62]:
#Ingrese la la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

query = """ SELECT id, name FROM Country WHERE name = 'Italy';"""

#No modificar lo siguiente:
countries_equal = pd.read_sql(query, conn)
countries_equal

      id   name
0  10257  Italy

6.4.2 Práctica: Traer la tabla de países sin Polonia
Deben traer la tabla de países sin Poland. La tabla de resultados deberá contener los campos id y name de la tabla Country de la base de datos de Fútbol Europeo. No se debe utilizar NOT.

Para ello deberán escribir la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

Una vez que estén lo tengan listo, ejecuten (haciendo clic en ejecutar o Shift+Enter) el códido de abajo

In [63]:
#Ingrese la la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

query = """SELECT ID, name FROM Country WHERE name = 'Poland'; """

#No modificar lo siguiente:
countries_dif = pd.read_sql(query, conn)
countries_dif

      id    name
0  15722  Poland

6.4.3 Práctica: Listar los jugadores que pesen entre 174 y 176 libras
Queremos listar a los jugadores que cumplan con la condición de pesar entre 174 y 176 libras. En la tabla de resultados quiero ver los campos id,player_name, birthday, height y weight de los que cumplen la condición. Todos se encuentran en la tabla Player. Asimismo, debemos limitar la consulta a 30 registros.

Para ello deberán escribir la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

Una vez que estén lo tengan listo, ejecuten (haciendo clic en ejecutar o Shift+Enter) el códido de abajo

In [74]:
#Ingrese la la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

query = """SELECT  id,player_name, birthday, height, weight FROM Player WHERE weight BETWEEN 174 AND 176 LIMIT 30; """

#No modificar lo siguiente:
players_weight = pd.read_sql(query, conn)
players_weight

     id            player_name             birthday  height  weight
0    17  Aaron Taylor-Sinclair  1991-04-08 00:00:00  182.88     176
1    34           Abdou Traore  1988-01-17 00:00:00  180.34     174
2    39           Abdoulaye Ba  1991-01-01 00:00:00  198.12     174
3    43       Abdoulaye Diallo  1992-03-30 00:00:00  187.96     174
4    61           Abel Aguilar  1985-01-06 00:00:00  185.42     176
5    68     Abella Perez Damia  1982-04-15 00:00:00  187.96     174
6    74       Abraham Gonzalez  1985-07-16 00:00:00  177.80     176
7    79          Achille Coser  1982-07-14 00:00:00  185.42     174
8    89             Adam Banas  1982-12-25 00:00:00  185.42     174
9    90            Adam Bodzek  1985-09-07 00:00:00  182.88     174
10  102          Adam Dzwigala  1995-09-25 00:00:00  185.42     176
11  133       Adam Waszkiewicz  1993-12-06 00:00:00  182.88     174
12  136         Adama Francois  1989-11-30 00:00:00  193.04     176
13  153         Admir Aganovic  1986-08-25 00:00:00  182.88     176
14  154          Admir Mehmedi  1991-03-16 00:00:00  182.88     176
15  194                Adriano  1980-01-29 00:00:00  182.88     176
16  209           Agon Mehmeti  1989-11-20 00:00:00  182.88     174
17  210       Agustin Vuletich  1991-11-03 00:00:00  185.42     174
18  221       Ahmed Saied Okka  1984-03-13 00:00:00  185.42     174
19  242             Akpo Sodje  1981-01-31 00:00:00  187.96     176
20  257            Alan Kardec  1989-01-12 00:00:00  187.96     176
21  268          Alassane Plea  1993-03-10 00:00:00  180.34     174
22  283          Albert Streit  1980-03-28 00:00:00  180.34     174
23  284       Alberto Aquilani  1984-07-07 00:00:00  185.42     174
24  285          Alberto Botia  1989-01-27 00:00:00  187.96     176
25  293      Alberto Gilardino  1982-07-05 00:00:00  182.88     174
26  298       Alberto Luque,21  1978-03-11 00:00:00  182.88     176
27  301       Alberto Paloschi  1990-01-04 00:00:00  182.88     176
28  313         Albion Avdijaj  1994-01-12 00:00:00  190.50     176
29  319          Aleandro Rosi  1987-05-17 00:00:00  182.88     176

6.4.4 Práctica: Listar a los Messi de la base de datos de jugadores
Queremos listar a los jugadores que cumplan con la condición de tener la palabra 'Messi' en su nombre. En la tabla de resultados quiero ver los campos id,player_name, birthday, height y weight de los que cumplen la condición. Todos se encuentran en la tabla Player.

Para ello deberán escribir la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

Una vez que estén lo tengan listo, ejecuten (haciendo clic en ejecutar o Shift+Enter) el códido de abajo

In [73]:
#Ingrese la la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

query = query = """SELECT id, player_name, birthday, height, weight FROM Player WHERE player_name LIKE '%Messi%';"""

#No modificar lo siguiente:
players_messi = pd.read_sql(query, conn)
players_messi

     id   player_name             birthday  height  weight
0  6176  Lionel Messi  1987-06-24 00:00:00  170.18     159

Alias AS
Los alias en SQL se utilizan para dar a una tabla o a una columna, un nombre temporal. Se utilizan a menudo para hacer más legibles los nombres de las columnas. Un alias sólo existe durante la duración de la consulta.

Sintaxis de AS:

SELECT column_name AS alias_name

FROM table_name AS other_alias;

7. Sentencia ORDER BY
La sentencia ORDER BY se utiliza para ordenar el conjunto de resultados en orden ascendente o descendente. Por defecto, los registros se ordenan en orden ascendente ASC. Para ordenar los registros en orden descendente, utilice la palabra DESC.

Sintaxis de ORDER BY

SELECT column1, column2, ...

FROM table_name

WHERE condition

ORDER BY column2 ASC|DESC;